[theme]
base = "dark"
primaryColor = "#1e88e5"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[runner]
magicEnabled = true
fastReruns = true
